-- 数据库表结构更新脚本
-- 适用于已经存在数据库但字段不匹配的情况

USE help;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS salt VARCHAR(64) NULL COMMENT '随机盐值' AFTER password;

ALTER TABLE volunteer_orders
ADD COLUMN IF NOT EXISTS created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' AFTER images,
ADD COLUMN IF NOT EXISTS updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' AFTER created_at;

SHOW CREATE TABLE users;
SHOW CREATE TABLE help_requests;
SHOW CREATE TABLE volunteer_orders;
SHOW CREATE TABLE chat_messages;
SHOW CREATE TABLE reviews;
